
CREATE PROCEDURE GET_Manager_Position
(
@M_Email NVARCHAR(255)
)
AS

SELECT TOP 1 POSITIONID  FROM
[dbo].[HcmWorkerStaging] W
INNER JOIN HcmPositionV2Staging P on P.WORKERPERSONNELNUMBER = W.PERSONNELNUMBER
WHERE USER_ = LOWER(LEFT(@M_Email, CHARINDEX('@', @M_Email) - 1))