CREATE PROCEDURE GET_Position_Details (@Placement_ID nvarchar(256))
AS
SELECT [TS]
      ,[Placment_Id]
      ,[Vacancy_ID]
      ,[Consultant_ID]
      ,[Candidate_ID]
      ,[Manager_Contact_ID]
      ,[FirstName]
      ,[LastName]
      ,[Nickame]
      ,[PersonalEmail]
      ,[PersonalMobile]
      ,[StartDate]
      ,[EndDate]
      ,[ClientName]
      ,[ClientGuid]
      ,[DOB]
      ,[HRClientGUID]
      ,[HRCompRegion]
      ,[Office]
      ,[Brand]
      ,[Team]
      ,[HKEY]
      ,[Is_Latest]
      ,[DateRecord]
      ,[SharepointLocation]
      ,[Legalentity]
      ,[ManagerHRIS]
      ,[ManagerName]
      ,[Title]
      ,[Vacancy_Title]
      ,[Consultant_Email]
      ,[Consultant_Name]
  FROM [dbo].[Placement_Transaction]
  WHERE [Placment_Id] = @Placement_Id