CREATE PROCEDURE HRIS_Current
AS
BEGIN
TRUNCATE TABLE Current_Position;



INSERT INTO Current_Position
SELECT DISTINCT
w.PERSONNELNUMBER, cp.POSITIONID, w.PARTYNUMBER
FROM (SELECT DISTINCT * FROM [dbo].[HcmWorkerStaging]) w 
LEFT JOIN (
	SELECT 
	w.PERSONNELNUMBER, 
	CASE WHEN ns.POSITIONID IS NULL THEN CASE WHEN wp.POSITIONID IS NULL THEN nop.POSITIONID ELSE wp.POSITIONID END ELSE ns.POSITIONID END AS POSITIONID 
	FROM 
	(SELECT DISTINCT * FROM [dbo].[HcmWorkerStaging]) w 
	LEFT JOIN HcmEmploymentStaging nse ON w.PERSONNELNUMBER = nse.PERSONNELNUMBER AND nse.EMPLOYMENTSTARTDATE>CURRENT_TIMESTAMP
	LEFT JOIN dbo.HcmPositionWorkerAssignmentV2Staging wp ON w.PERSONNELNUMBER = wp.PERSONNELNUMBER AND wp.ISPRIMARYPOSITION = 1
	LEFT JOIN dbo.HcmPositionWorkerAssignmentV2Staging ns ON nse.PERSONNELNUMBER = ns.PERSONNELNUMBER AND ns.VALIDFROM > CURRENT_TIMESTAMP
	LEFT JOIN dbo.HcmPositionV2Staging p ON p.POSITIONID = wp.POSITIONID
	LEFT JOIN dbo.HcmPositionV2Staging nsp ON nsp.POSITIONID = ns.POSITIONID
	LEFT JOIN (
		SELECT lp.POSITIONID, lp.PERSONNELNUMBER 
		FROM dbo.HcmPositionWorkerAssignmentV2Staging lp 
		INNER JOIN (
			SELECT PERSONNELNUMBER, MAX(VALIDTO) AS MD 
			FROM dbo.HcmPositionWorkerAssignmentV2Staging
			GROUP BY PERSONNELNUMBER
		) md ON md.PERSONNELNUMBER = lp.PERSONNELNUMBER AND lp.VALIDTO = md.MD
	) nop ON nop.PERSONNELNUMBER = w.PERSONNELNUMBER
	LEFT JOIN dbo.HcmPositionV2Staging mdp ON mdp.POSITIONID = nop.POSITIONID
) cp ON cp.PERSONNELNUMBER = w.PERSONNELNUMBER 
WHERE w.PERSONNELNUMBER <> 'E-002279'
END