CREATE PROCEDURE UPD_Placement_Transaction_Dupes
AS
UPDATE [Placement_Transaction] 
SET HKEY = 
	  HASHBYTES('md5',CONCAT(
      [Placment_Id]
      ,[Vacancy_ID]
      ,[Consultant_ID]
      ,[Candidate_ID]
      ,[Manager_Contact_ID]
      ,[FirstName]
      ,[LastName]
      ,[Nickame]
      ,[PersonalEmail]
      ,[PersonalMobile]
      ,[StartDate]
      ,[EndDate]
      ,[ClientName]
      ,[ClientGuid]
      ,[DOB]
      ,[HRClientGUID]
      ,[HRCompRegion]
      ,[Office]
      ,[Brand]
      ,[Team]
      ,[SharepointLocation]
      ,[Legalentity]
      ,[ManagerHRIS]
      ,[ManagerName]
      ,[Title]
      ,[Vacancy_Title]
      ,[Consultant_Email]
      ,[Consultant_Name]
      ,[Salary]
      ,[Address1]
      ,[Address2]
      ,[Address3]
      ,[Town_City]
      ,[County]
      ,[Postcode]
      ,[Country]
      ,[Pers_Email]
      ,[Pers_Mobile]))
  FROM [dbo].[Placement_Transaction]
  WHERE HKEY IS NULL
