CREATE TABLE [dbo].[Current_Position] (
    [PERSONNELNUMBER] VARCHAR (20) NOT NULL,
    [POSITIONID]      VARCHAR (20) NULL,
    [PARTYNUMBER]     VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([PERSONNELNUMBER] ASC)
);

