CREATE TABLE [dbo].[Email_Items] (
    [FirstName]         VARCHAR (256)  NULL,
    [LastName]          VARCHAR (256)  NULL,
    [KnownAs]           VARCHAR (256)  NULL,
    [DOB]               DATE           NULL,
    [ManagerName]       VARCHAR (256)  NULL,
    [ManagerHRIS]       VARCHAR (256)  NULL,
    [Legalentity]       NVARCHAR (10)  NULL,
    [DateRecord]        DATE           NULL,
    [StartDate]         DATE           NULL,
    [Office]            VARCHAR (256)  NULL,
    [Brand]             VARCHAR (256)  NULL,
    [Team]              VARCHAR (256)  NULL,
    [Title]             NVARCHAR (255) NULL,
    [Consultant_Email]  NVARCHAR (255) NULL,
    [Consultant_Name]   NVARCHAR (255) NULL,
    [Vacancy_Title]     NVARCHAR (255) NULL,
    [Personnell_Number] VARCHAR (20)   NULL,
    [PositionID]        NVARCHAR (256) NULL,
    [Vacancy_Office]    NVARCHAR (255) NULL,
    [Vacancy_ID]        VARCHAR (256)  NULL,
    [UnkOffice]         VARCHAR (5)    NOT NULL,
    [UnkBrand]          VARCHAR (5)    NOT NULL,
    [UnkTeam]           VARCHAR (5)    NOT NULL,
    [UnkKnownAs]        VARCHAR (5)    NOT NULL,
    [UnkDOB]            VARCHAR (5)    NOT NULL,
    [Salary]            NVARCHAR (256) NULL,
    [Address1]          NVARCHAR (256) NULL,
    [Address2]          NVARCHAR (256) NULL,
    [Address3]          NVARCHAR (256) NULL,
    [Town_City]         NVARCHAR (256) NULL,
    [County]            NVARCHAR (256) NULL,
    [Postcode]          NVARCHAR (256) NULL,
    [Country]           NVARCHAR (256) NULL,
    [Pers_Email]        NVARCHAR (256) NULL,
    [Pers_Mobile]       NVARCHAR (256) NULL
);

