CREATE TABLE [dbo].[HcmCompFixedPlanTableStaging] (
    [DEFINITIONGROUP]       NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [EXECUTIONID]           NVARCHAR (90) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ISSELECTED]            INT           NOT NULL,
    [TRANSFERSTATUS]        INT           NOT NULL,
    [CONTROLPOINT]          NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CURRENCY]              NVARCHAR (3)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DESCRIPTION]           NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [RECOMMENDATIONALLOWED] INT           NOT NULL,
    [COMPENSATIONSTRUCTURE] NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [HIRERULE]              INT           NOT NULL,
    [MARKETPRICEINDICATOR]  INT           NOT NULL,
    [PAYFREQUENCY]          NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PLAN_]                 NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [OUTOFRANGETOLERANCE]   INT           NOT NULL,
    [TYPE]                  INT           NOT NULL,
    [EFFECTIVEDATE]         DATETIME      NOT NULL,
    [EXPIRATIONDATE]        DATETIME      NOT NULL,
    [PARTITION]             NVARCHAR (20) NOT NULL,
    [DATAAREAID]            NVARCHAR (4)  NOT NULL,
    [SYNCSTARTDATETIME]     DATETIME      NOT NULL,
    CONSTRAINT [PK_HcmCompFixedPlanTableStaging] UNIQUE NONCLUSTERED ([EXECUTIONID] ASC, [PLAN_] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_DATAAREAID]
    ON [dbo].[HcmCompFixedPlanTableStaging]([PARTITION] ASC, [DATAAREAID] ASC);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_HcmCompFixedPlanTableStaging]
    ON [dbo].[HcmCompFixedPlanTableStaging];

