CREATE TABLE [dbo].[HcmEthnicOriginStaging] (
    [DEFINITIONGROUP]   NVARCHAR (60) NOT NULL,
    [EXECUTIONID]       NVARCHAR (90) NOT NULL,
    [ISSELECTED]        INT           NOT NULL,
    [TRANSFERSTATUS]    INT           NOT NULL,
    [DESCRIPTION]       NVARCHAR (60) NOT NULL,
    [ETHNICORIGINID]    NVARCHAR (15) NOT NULL,
    [EEOETHNICORIGIN]   INT           NOT NULL,
    [PARTITION]         NVARCHAR (20) NOT NULL,
    [SYNCSTARTDATETIME] DATETIME      NOT NULL,
    [RECID]             BIGINT        NOT NULL
);

