CREATE TABLE [dbo].[HcmIssuingAgencyStaging] (
    [ADDRESSCOUNTRYREGIONISOCODE] NVARCHAR (2)   NOT NULL,
    [DEFINITIONGROUP]             NVARCHAR (60)  NOT NULL,
    [EXECUTIONID]                 NVARCHAR (90)  NOT NULL,
    [ISSELECTED]                  INT            NOT NULL,
    [TRANSFERSTATUS]              INT            NOT NULL,
    [EMAIL]                       NVARCHAR (80)  NOT NULL,
    [ISSUINGAGENCY]               NVARCHAR (15)  NOT NULL,
    [NAME]                        NVARCHAR (60)  NOT NULL,
    [PAGER]                       NVARCHAR (20)  NOT NULL,
    [TELEPHONE]                   NVARCHAR (20)  NOT NULL,
    [EXTENSION]                   NVARCHAR (10)  NOT NULL,
    [MOBILEPHONE]                 NVARCHAR (20)  NOT NULL,
    [SMS]                         NVARCHAR (80)  NOT NULL,
    [FAX]                         NVARCHAR (20)  NOT NULL,
    [TELEXNUMBER]                 NVARCHAR (20)  NOT NULL,
    [INTERNETADDRESS]             NVARCHAR (255) NOT NULL,
    [ADDRESSLOCATIONID]           NVARCHAR (30)  NOT NULL,
    [ADDRESSDESCRIPTION]          NVARCHAR (60)  NOT NULL,
    [ADDRESSCOUNTRYREGIONID]      NVARCHAR (10)  NOT NULL,
    [ADDRESSZIPCODE]              NVARCHAR (10)  NOT NULL,
    [ADDRESSCOUNTY]               NVARCHAR (30)  NOT NULL,
    [ADDRESSSTREET]               NVARCHAR (250) NOT NULL,
    [ADDRESSCITY]                 NVARCHAR (60)  NOT NULL,
    [ADDRESSSTATE]                NVARCHAR (10)  NOT NULL,
    [ADDRESSVALIDFROM]            DATETIME       NOT NULL,
    [ADDRESSVALIDTO]              DATETIME       NOT NULL,
    [PARTITION]                   NVARCHAR (20)  NOT NULL,
    [SYNCSTARTDATETIME]           DATETIME       NOT NULL,
    [RECID]                       BIGINT         NOT NULL
);

