CREATE TABLE [dbo].[HcmPositionDefaultDimensionStaging] (
    [DIMENSIONDISPLAYVALUE]  NVARCHAR (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DEFINITIONGROUP]        NVARCHAR (60)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [EXECUTIONID]            NVARCHAR (90)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ISSELECTED]             INT            NOT NULL,
    [TRANSFERSTATUS]         INT            NOT NULL,
    [LEGALENTITYDATAAREA]    NVARCHAR (4)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DISTRIBUTIONTEMPLATEID] NVARCHAR (40)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONID]             NVARCHAR (25)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PARTITION]              NVARCHAR (20)  NOT NULL,
    [DATAAREAID]             NVARCHAR (4)   NOT NULL,
    [SYNCSTARTDATETIME]      DATETIME       NOT NULL,
    [RECID]                  BIGINT         NOT NULL,
    CONSTRAINT [PK_HcmPositionDefaultDimensionStaging] UNIQUE NONCLUSTERED ([EXECUTIONID] ASC, [LEGALENTITYDATAAREA] ASC, [POSITIONID] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_DATAAREAID]
    ON [dbo].[HcmPositionDefaultDimensionStaging]([PARTITION] ASC, [DATAAREAID] ASC);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_HcmPositionDefaultDimensionStaging]
    ON [dbo].[HcmPositionDefaultDimensionStaging];

