CREATE TABLE [dbo].[HcmPositionWorkerAssignmentV2Staging] (
    [ISPRIMARYPOSITION] INT           NOT NULL,
    [DEFINITIONGROUP]   NVARCHAR (60) NOT NULL,
    [EXECUTIONID]       NVARCHAR (90) NOT NULL,
    [ISSELECTED]        INT           NOT NULL,
    [TRANSFERSTATUS]    INT           NOT NULL,
    [POSITIONID]        NVARCHAR (25) NOT NULL,
    [PERSONNELNUMBER]   NVARCHAR (25) NOT NULL,
    [REASONCODEID]      NVARCHAR (15) NOT NULL,
    [VALIDFROM]         DATETIME      NOT NULL,
    [VALIDTO]           DATETIME      NOT NULL,
    [PARTITION]         NVARCHAR (20) NOT NULL,
    [SYNCSTARTDATETIME] DATETIME      NOT NULL,
    [RECID]             BIGINT        NOT NULL
);

