CREATE TABLE [dbo].[HcmPositionDetailStaging] (
    [DEFINITIONGROUP]        NVARCHAR (60)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [EXECUTIONID]            NVARCHAR (90)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ISSELECTED]             INT             NOT NULL,
    [TRANSFERSTATUS]         INT             NOT NULL,
    [AVAILABLEFORASSIGNMENT] DATETIME        NOT NULL,
    [COMPENSATIONREGIONID]   NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DEPARTMENTNUMBER]       NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DESCRIPTION]            NVARCHAR (60)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [FULLTIMEEQUIVALENT]     NUMERIC (32, 6) NOT NULL,
    [JOBID]                  NVARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONID]             NVARCHAR (25)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONTYPEID]         NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TITLEID]                NVARCHAR (65)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [VALIDFROM]              DATETIME        NOT NULL,
    [VALIDTO]                DATETIME        NOT NULL,
    [JOBFAMILYID]            NVARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PARTITION]              NVARCHAR (20)   NOT NULL,
    [TEAM_CUSTOM]            NVARCHAR (75)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [BRAND_CUSTOM]           NVARCHAR (75)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SUBTEAM_CUSTOM]         NVARCHAR (75)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [OFFICE_CUSTOM]          NVARCHAR (75)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CODE_CUSTOM]            NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SYNCSTARTDATETIME]      DATETIME        NOT NULL,
    [RECID]                  BIGINT          NOT NULL,
    CONSTRAINT [PK_HcmPositionDetailStaging] UNIQUE NONCLUSTERED ([EXECUTIONID] ASC, [POSITIONID] ASC, [VALIDFROM] ASC, [VALIDTO] ASC, [PARTITION] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_HcmPositionDetailStaging]
    ON [dbo].[HcmPositionDetailStaging];

