CREATE TABLE [dbo].[HcmPersonalContactPersonStaging] (
    [ISBENEFICIARY]                       INT           NOT NULL,
    [ISEMERGENCYCONTACT]                  INT           NOT NULL,
    [ISDEPENDENT]                         INT           NOT NULL,
    [DEFINITIONGROUP]                     NVARCHAR (60) NOT NULL,
    [EXECUTIONID]                         NVARCHAR (90) NOT NULL,
    [ISSELECTED]                          INT           NOT NULL,
    [TRANSFERSTATUS]                      INT           NOT NULL,
    [WORKERPERSONNELNUMBER]               NVARCHAR (25) NOT NULL,
    [CONTACTPERSONPARTYNUMBER]            NVARCHAR (40) NOT NULL,
    [RELATIONSHIPTYPE]                    NVARCHAR (20) NOT NULL,
    [RELATIONSHIPVALIDFROM]               DATETIME      NOT NULL,
    [RELATIONSHIPVALIDTO]                 DATETIME      NOT NULL,
    [CONTACTFIRSTNAME]                    NVARCHAR (25) NOT NULL,
    [CONTACTMIDDLENAME]                   NVARCHAR (25) NOT NULL,
    [CONTACTLASTNAMEPREFIX]               NVARCHAR (25) NOT NULL,
    [CONTACTLASTNAME]                     NVARCHAR (25) NOT NULL,
    [EMERGENCYCONTACTPRIMARYSECONDARY]    INT           NOT NULL,
    [ISDEPENDENTCOURTORDERED]             INT           NOT NULL,
    [ISDEPENDENTDOMESTICPARTNERVERIFIED]  INT           NOT NULL,
    [DEPENDENTCOURTORDEREDEXPIRATIONDATE] DATETIME      NOT NULL,
    [GENDER]                              INT           NOT NULL,
    [BIRTHDATE]                           DATETIME      NOT NULL,
    [ISFULLTIMESTUDENT]                   INT           NOT NULL,
    [ISDISABLED]                          INT           NOT NULL,
    [DISABLEDVERIFICATIONDATE]            DATETIME      NOT NULL,
    [PARTITION]                           NVARCHAR (20) NOT NULL,
    [SYNCSTARTDATETIME]                   DATETIME      NOT NULL,
    [RECID]                               BIGINT        NOT NULL
);

