CREATE TABLE [dbo].[HcmPersonCertificateStaging] (
    [DEFINITIONGROUP]   NVARCHAR (60)  NOT NULL,
    [EXECUTIONID]       NVARCHAR (90)  NOT NULL,
    [ISSELECTED]        INT            NOT NULL,
    [TRANSFERSTATUS]    INT            NOT NULL,
    [CERTIFICATETYPEID] NVARCHAR (15)  NOT NULL,
    [STARTDATE]         DATETIME       NOT NULL,
    [ENDDATE]           DATETIME       NOT NULL,
    [NOTES]             NVARCHAR (500) NOT NULL,
    [PARTYNUMBER]       NVARCHAR (40)  NOT NULL,
    [PARTITION]         NVARCHAR (20)  NOT NULL,
    [SYNCSTARTDATETIME] DATETIME       NOT NULL,
    [RECID]             BIGINT         NOT NULL,
    CONSTRAINT [PK_HcmPersonCertificateStaging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [CERTIFICATETYPEID] ASC, [STARTDATE] ASC, [PARTYNUMBER] ASC, [PARTITION] ASC)
);

