CREATE TABLE [dbo].[HcmPositionTimelineStaging] (
    [VALIDTO]                                  DATETIME         NOT NULL,
    [DEFINITIONGROUP]                          NVARCHAR (60)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [EXECUTIONID]                              NVARCHAR (90)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ISSELECTED]                               INT              NOT NULL,
    [TRANSFERSTATUS]                           INT              NOT NULL,
    [AVAILABLEFORASSIGNMENT]                   DATETIME         NOT NULL,
    [DEFAULTFULLTIMEEQUIVALENCY]               NUMERIC (32, 6)  NOT NULL,
    [DESCRIPTION]                              NVARCHAR (60)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [EXTERNALSURVEYCODE]                       NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [FULLTIMEEQUIVALENCY]                      NUMERIC (32, 6)  NOT NULL,
    [JOBDETAILCREATEDBY]                       NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [JOBDETAILCREATEDDATETIME]                 DATETIME         NOT NULL,
    [JOBDETAILDESCRIPTION]                     NVARCHAR (60)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [JOBDETAILMODIFIEDBY]                      NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [JOBDETAILVALIDFROM]                       DATETIME         NOT NULL,
    [JOBDETAILVALIDTO]                         DATETIME         NOT NULL,
    [MARKETCONTROLPAY]                         NUMERIC (32, 16) NOT NULL,
    [MARKETMAXIMUMPAY]                         NUMERIC (32, 16) NOT NULL,
    [MARKETMINIMUMPAY]                         NUMERIC (32, 16) NOT NULL,
    [MARKETSOURCE]                             NVARCHAR (60)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [JOBDETAILMODIFIEDDATETIME]                DATETIME         NOT NULL,
    [PAYROLLNORMALHOURS]                       NUMERIC (32, 6)  NOT NULL,
    [PAYROLLPOSITIONDETAILSVALIDFROM]          DATETIME         NOT NULL,
    [PAYROLLPOSITIONDETAILSVALIDTO]            DATETIME         NOT NULL,
    [POSITION]                                 BIGINT           NOT NULL,
    [POSITIONCREATEDBY]                        NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONCREATEDDATETIME]                  DATETIME         NOT NULL,
    [POSITIONDETAILCREATEDBY]                  NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONDETAILCREATEDDATETIME]            DATETIME         NOT NULL,
    [POSITIONDETAILMODIFIEDBY]                 NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONDETAILMODIFIEDDATETIME]           DATETIME         NOT NULL,
    [POSITIONDETAILVALIDFROM]                  DATETIME         NOT NULL,
    [POSITIONDETAILVALIDTO]                    DATETIME         NOT NULL,
    [POSITIONID]                               NVARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONMODIFIEDBY]                       NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONMODIFIEDDATETIME]                 DATETIME         NOT NULL,
    [POSITIONWORKERASSIGNMENTCREATEDBY]        NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONWORKERASSIGNMENTCREATEDDATETIME]  DATETIME         NOT NULL,
    [POSITIONWORKERASSIGNMENTMODIFIEDBY]       NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONWORKERASSIGNMENTMODIFIEDDATETIME] DATETIME         NOT NULL,
    [POSITIONWORKERASSIGNMENTVALIDFROM]        DATETIME         NOT NULL,
    [POSITIONWORKERASSIGNMENTVALIDTO]          DATETIME         NOT NULL,
    [VALIDFROM]                                DATETIME         NOT NULL,
    [JOBFUNCTIONID]                            NVARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [JOBID]                                    NVARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [JOBTYPEID]                                NVARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [COMPENSATIONLEVELID]                      NVARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [COMPLOCATIONID]                           NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PAYCYCLEID]                               NVARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [POSITIONTYPEID]                           NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [REASONCODEID]                             NVARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SURVEYCOMPANYID]                          NVARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PERSONNELNUMBER]                          NVARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PAIDBYLEGALENTITYID]                      NVARCHAR (4)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DEPARTMENTNUMBER]                         NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TITLEID]                                  NVARCHAR (65)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PARTITION]                                NVARCHAR (20)    NOT NULL,
    [SYNCSTARTDATETIME]                        DATETIME         NOT NULL,
    CONSTRAINT [PK_HcmPositionTimelineStaging] UNIQUE NONCLUSTERED ([EXECUTIONID] ASC, [POSITIONID] ASC, [PARTITION] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_HcmPositionTimelineStaging]
    ON [dbo].[HcmPositionTimelineStaging];

