CREATE TABLE [dbo].[LeaveBankTransactionV2Staging] (
    [DEFINITIONGROUP]   NVARCHAR (60)    NOT NULL,
    [EXECUTIONID]       NVARCHAR (90)    NOT NULL,
    [ISSELECTED]        INT              NOT NULL,
    [TRANSFERSTATUS]    INT              NOT NULL,
    [AMOUNT]            NUMERIC (32, 6)  NOT NULL,
    [TRANSACTIONDATE]   DATETIME         NOT NULL,
    [TRANSACTIONNUMBER] NUMERIC (32, 16) NOT NULL,
    [TRANSACTIONTYPE]   INT              NOT NULL,
    [LEAVETYPEID]       NVARCHAR (30)    NOT NULL,
    [PERSONNELNUMBER]   NVARCHAR (25)    NOT NULL,
    [LEAVEPLANID]       NVARCHAR (30)    NOT NULL,
    [HALFDAYDEFINITION] INT              NOT NULL,
    [PARTITION]         NVARCHAR (20)    NOT NULL,
    [COMMENT_]          NVARCHAR (MAX)   NULL,
    [DATAAREAID]        NVARCHAR (4)     NOT NULL,
    [SYNCSTARTDATETIME] DATETIME         NOT NULL,
    [RECID]             BIGINT           NOT NULL,
    CONSTRAINT [PK_LeaveBankTransactionV2Staging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [TRANSACTIONDATE] ASC, [TRANSACTIONNUMBER] ASC, [TRANSACTIONTYPE] ASC, [LEAVETYPEID] ASC, [PERSONNELNUMBER] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);

