CREATE TABLE [dbo].[Placement_Transaction] (
    [TS]                 ROWVERSION     NOT NULL,
    [Placment_Id]        VARCHAR (256)  NULL,
    [Vacancy_ID]         VARCHAR (256)  NULL,
    [Consultant_ID]      VARCHAR (256)  NULL,
    [Candidate_ID]       VARCHAR (256)  NULL,
    [Manager_Contact_ID] VARCHAR (256)  NULL,
    [FirstName]          VARCHAR (256)  NULL,
    [LastName]           VARCHAR (256)  NULL,
    [Nickame]            VARCHAR (256)  NULL,
    [PersonalEmail]      VARCHAR (256)  NULL,
    [PersonalMobile]     VARCHAR (256)  NULL,
    [StartDate]          DATE           NULL,
    [EndDate]            DATETIME       DEFAULT ('2154-12-31 23:59:59.000') NULL,
    [ClientName]         VARCHAR (256)  NULL,
    [ClientGuid]         VARCHAR (256)  NULL,
    [DOB]                DATE           NULL,
    [HRClientGUID]       VARCHAR (256)  NULL,
    [HRCompRegion]       VARCHAR (256)  NULL,
    [Office]             VARCHAR (256)  NULL,
    [Brand]              VARCHAR (256)  NULL,
    [Team]               VARCHAR (256)  NULL,
    [HKEY]               BINARY (32)    NULL,
    [Is_Latest]          INT            DEFAULT ((1)) NULL,
    [DateRecord]         DATE           DEFAULT (getdate()) NULL,
    [SharepointLocation] VARCHAR (MAX)  NULL,
    [Legalentity]        NVARCHAR (10)  DEFAULT ('PI04') NULL,
    [ManagerHRIS]        VARCHAR (256)  NULL,
    [ManagerName]        VARCHAR (256)  NULL,
    [Title]              NVARCHAR (255) NULL,
    [Vacancy_Title]      NVARCHAR (255) NULL,
    [Consultant_Email]   NVARCHAR (255) NULL,
    [Consultant_Name]    NVARCHAR (255) NULL,
    [Salary]             NVARCHAR (256) NULL,
    [Address1]           VARCHAR (256)  NULL,
    [Address2]           VARCHAR (256)  NULL,
    [Address3]           VARCHAR (256)  NULL,
    [Town_City]          VARCHAR (256)  NULL,
    [County]             VARCHAR (256)  NULL,
    [Postcode]           VARCHAR (256)  NULL,
    [Country]            VARCHAR (256)  NULL,
    [Pers_Email]         VARCHAR (256)  NULL,
    [Pers_Mobile]        VARCHAR (256)  NULL
);

