CREATE TABLE [hr].[mshr_dirpersonentity] (
    [mshr_partynumber]                       NVARCHAR (MAX)   NULL,
    [mshr_name]                              NVARCHAR (MAX)   NULL,
    [mshr_namealias]                         NVARCHAR (MAX)   NULL,
    [mshr_knownas]                           NVARCHAR (MAX)   NULL,
    [mshr_languageid]                        NVARCHAR (MAX)   NULL,
    [mshr_addressbooks]                      NVARCHAR (MAX)   NULL,
    [mshr_anniversaryday]                    INT              NULL,
    [mshr_anniversarymonth]                  INT              NULL,
    [mshr_anniversaryyear]                   INT              NULL,
    [mshr_birthday]                          INT              NULL,
    [mshr_birthmonth]                        INT              NULL,
    [mshr_birthyear]                         INT              NULL,
    [mshr_childrennames]                     NVARCHAR (MAX)   NULL,
    [mshr_gender]                            INT              NULL,
    [mshr_hobbies]                           NVARCHAR (MAX)   NULL,
    [mshr_initials]                          NVARCHAR (MAX)   NULL,
    [mshr_maritalstatus]                     INT              NULL,
    [mshr_phoneticfirstname]                 NVARCHAR (MAX)   NULL,
    [mshr_phoneticlastname]                  NVARCHAR (MAX)   NULL,
    [mshr_phoneticmiddlename]                NVARCHAR (MAX)   NULL,
    [mshr_personalsuffix]                    NVARCHAR (MAX)   NULL,
    [mshr_personaltitle]                     NVARCHAR (MAX)   NULL,
    [mshr_professionalsuffix]                NVARCHAR (MAX)   NULL,
    [mshr_professionaltitle]                 NVARCHAR (MAX)   NULL,
    [mshr_fullprimaryaddress]                NVARCHAR (MAX)   NULL,
    [mshr_addresscity]                       NVARCHAR (MAX)   NULL,
    [mshr_addresscountryregionid]            NVARCHAR (MAX)   NULL,
    [mshr_addresscountryregionisocode]       NVARCHAR (MAX)   NULL,
    [mshr_addresscounty]                     NVARCHAR (MAX)   NULL,
    [mshr_addressdistrictname]               NVARCHAR (MAX)   NULL,
    [mshr_addresslatitude]                   DECIMAL (38, 18) NULL,
    [mshr_addresslocationid]                 NVARCHAR (MAX)   NULL,
    [mshr_addresslocationroles]              NVARCHAR (MAX)   NULL,
    [mshr_addresslongitude]                  DECIMAL (38, 18) NULL,
    [mshr_addressstate]                      NVARCHAR (MAX)   NULL,
    [mshr_addressstreet]                     NVARCHAR (MAX)   NULL,
    [mshr_addressvalidfrom]                  DATETIME2 (7)    NULL,
    [mshr_addressvalidto]                    DATETIME2 (7)    NULL,
    [mshr_addresszipcode]                    NVARCHAR (MAX)   NULL,
    [mshr_addressisprivate]                  INT              NULL,
    [mshr_addressdescription]                NVARCHAR (MAX)   NULL,
    [mshr_primarycontactemail]               NVARCHAR (MAX)   NULL,
    [mshr_primarycontactemaildescription]    NVARCHAR (MAX)   NULL,
    [mshr_primarycontactemailisim]           INT              NULL,
    [mshr_primarycontactemailpurpose]        NVARCHAR (MAX)   NULL,
    [mshr_primarycontactfax]                 NVARCHAR (MAX)   NULL,
    [mshr_primarycontactfaxdescription]      NVARCHAR (MAX)   NULL,
    [mshr_primarycontactfaxextension]        NVARCHAR (MAX)   NULL,
    [mshr_primarycontactfaxpurpose]          NVARCHAR (MAX)   NULL,
    [mshr_primarycontactphone]               NVARCHAR (MAX)   NULL,
    [mshr_primarycontactphonedescription]    NVARCHAR (MAX)   NULL,
    [mshr_primarycontactphoneextension]      NVARCHAR (MAX)   NULL,
    [mshr_primarycontactphoneismobile]       INT              NULL,
    [mshr_primarycontactphonepurpose]        NVARCHAR (MAX)   NULL,
    [mshr_primarycontacttelex]               NVARCHAR (MAX)   NULL,
    [mshr_primarycontacttelexdescription]    NVARCHAR (MAX)   NULL,
    [mshr_primarycontacttelexpurpose]        NVARCHAR (MAX)   NULL,
    [mshr_primarycontacturl]                 NVARCHAR (MAX)   NULL,
    [mshr_primarycontacturldescription]      NVARCHAR (MAX)   NULL,
    [mshr_primarycontacturlpurpose]          NVARCHAR (MAX)   NULL,
    [mshr_primarycontactfacebook]            NVARCHAR (MAX)   NULL,
    [mshr_primarycontactfacebookdescription] NVARCHAR (MAX)   NULL,
    [mshr_primarycontactfacebookisprivate]   INT              NULL,
    [mshr_primarycontactfacebookpurpose]     NVARCHAR (MAX)   NULL,
    [mshr_primarycontactlinkedin]            NVARCHAR (MAX)   NULL,
    [mshr_primarycontactlinkedindescription] NVARCHAR (MAX)   NULL,
    [mshr_primarycontactlinkedinisprivate]   INT              NULL,
    [mshr_primarycontactlinkedinpurpose]     NVARCHAR (MAX)   NULL,
    [mshr_primarycontacttwitter]             NVARCHAR (MAX)   NULL,
    [mshr_primarycontacttwitterdescription]  NVARCHAR (MAX)   NULL,
    [mshr_primarycontacttwitterisprivate]    INT              NULL,
    [mshr_primarycontacttwitterpurpose]      NVARCHAR (MAX)   NULL,
    [mshr_partytype]                         NVARCHAR (MAX)   NULL,
    [mshr_namesequencedisplayas]             NVARCHAR (MAX)   NULL,
    [mshr_firstname]                         NVARCHAR (MAX)   NULL,
    [mshr_lastnameprefix]                    NVARCHAR (MAX)   NULL,
    [mshr_lastname]                          NVARCHAR (MAX)   NULL,
    [mshr_middlename]                        NVARCHAR (MAX)   NULL,
    [mshr_electroniclocationid]              NVARCHAR (MAX)   NULL,
    [mshr_dirpersonentityid]                 UNIQUEIDENTIFIER NULL
);

