CREATE TABLE [hr].[stg_tblcdmemployment] (
    [cdm_adjustedworkerstartdate]     DATETIME2 (7)    NULL,
    [cdm_companyid]                   UNIQUEIDENTIFIER NULL,
    [cdm_companyidname]               NVARCHAR (MAX)   NULL,
    [cdm_dimensiondisplayvalue]       NVARCHAR (MAX)   NULL,
    [cdm_employernoticeamount]        DECIMAL (38, 18) NULL,
    [cdm_employerunitofnotice]        INT              NULL,
    [cdm_employmentenddate]           DATETIME2 (7)    NULL,
    [cdm_employmentid]                UNIQUEIDENTIFIER NULL,
    [cdm_employmentnumber]            NVARCHAR (MAX)   NULL,
    [cdm_employmentstartdate]         DATETIME2 (7)    NULL,
    [cdm_exittype_custom]             INT              NULL,
    [cdm_extendedprobationend_custom] DATETIME2 (7)    NULL,
    [cdm_lastdateworked]              DATETIME2 (7)    NULL,
    [cdm_leavingreason_custom]        INT              NULL,
    [cdm_leavingreasonother_custom]   NVARCHAR (MAX)   NULL,
    [cdm_origprobationenddate_custom] DATETIME2 (7)    NULL,
    [cdm_payrollid_custom]            NVARCHAR (MAX)   NULL,
    [cdm_probationcomplete_custom]    BIT              NULL,
    [cdm_probationenddate]            DATETIME2 (7)    NULL,
    [cdm_probationpasseddate_custom]  DATETIME2 (7)    NULL,
    [cdm_rehire_custom]               BIT              NULL,
    [cdm_transitiondate]              DATETIME2 (7)    NULL,
    [cdm_transitionreasoncode]        UNIQUEIDENTIFIER NULL,
    [cdm_transitionreasoncodename]    NVARCHAR (MAX)   NULL,
    [cdm_validfrom]                   DATETIME2 (7)    NULL,
    [cdm_validto]                     DATETIME2 (7)    NULL,
    [cdm_workerid]                    UNIQUEIDENTIFIER NULL,
    [cdm_workeridname]                NVARCHAR (MAX)   NULL,
    [cdm_workernoticeamount]          DECIMAL (38, 18) NULL,
    [cdm_workerstartdate]             DATETIME2 (7)    NULL,
    [cdm_workertype]                  INT              NULL,
    [cdm_workerunitofnotice]          INT              NULL,
    [createdby]                       UNIQUEIDENTIFIER NULL,
    [createdbyname]                   NVARCHAR (MAX)   NULL,
    [createdbyyominame]               NVARCHAR (MAX)   NULL,
    [createdon]                       DATETIME2 (7)    NULL,
    [createdonbehalfby]               UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]           NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]       NVARCHAR (MAX)   NULL,
    [importsequencenumber]            INT              NULL,
    [modifiedby]                      UNIQUEIDENTIFIER NULL,
    [modifiedbyname]                  NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]              NVARCHAR (MAX)   NULL,
    [modifiedon]                      DATETIME2 (7)    NULL,
    [modifiedonbehalfby]              UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]          NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame]      NVARCHAR (MAX)   NULL,
    [overriddencreatedon]             DATETIME2 (7)    NULL,
    [ownerid]                         UNIQUEIDENTIFIER NULL,
    [owneridname]                     NVARCHAR (MAX)   NULL,
    [owneridtype]                     NVARCHAR (MAX)   NULL,
    [owneridyominame]                 NVARCHAR (MAX)   NULL,
    [owningbusinessunit]              UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]          NVARCHAR (MAX)   NULL,
    [owningteam]                      UNIQUEIDENTIFIER NULL,
    [owninguser]                      UNIQUEIDENTIFIER NULL,
    [statecode]                       INT              NULL,
    [statuscode]                      INT              NULL,
    [timezoneruleversionnumber]       INT              NULL,
    [utcconversiontimezonecode]       INT              NULL,
    [versionnumber]                   BIGINT           NULL
);

