CREATE TABLE [hr].[stg_tblcdmworker] (
    [cdm_anniversarydatetime]           DATETIME2 (7)    NULL,
    [cdm_assignments_custom]            NVARCHAR (MAX)   NULL,
    [cdm_birthdate]                     DATETIME2 (7)    NULL,
    [cdm_careertrack_custom]            INT              NULL,
    [cdm_description]                   NVARCHAR (MAX)   NULL,
    [cdm_eeoarmy_custom]                INT              NULL,
    [cdm_eeocareadult_custom]           INT              NULL,
    [cdm_eeocarepoc_custom]             INT              NULL,
    [cdm_eeocollege_custom]             INT              NULL,
    [cdm_eeogender_custom]              INT              NULL,
    [cdm_eeorace_custom]                INT              NULL,
    [cdm_eeoreligion_custom]            INT              NULL,
    [cdm_eeosexualorientation_custom]   INT              NULL,
    [cdm_eeotrans_custom]               INT              NULL,
    [cdm_emailaddress1]                 NVARCHAR (MAX)   NULL,
    [cdm_emailaddress2]                 NVARCHAR (MAX)   NULL,
    [cdm_facebookidentity]              NVARCHAR (MAX)   NULL,
    [cdm_feeearner_custom]              BIT              NULL,
    [cdm_firstname]                     NVARCHAR (MAX)   NULL,
    [cdm_fullname]                      NVARCHAR (MAX)   NULL,
    [cdm_gender]                        INT              NULL,
    [cdm_genderother_custom]            NVARCHAR (MAX)   NULL,
    [cdm_generation]                    NVARCHAR (MAX)   NULL,
    [cdm_isemailcontactallowed]         BIT              NULL,
    [cdm_isphonecontactallowed]         BIT              NULL,
    [cdm_knownas]                       NVARCHAR (MAX)   NULL,
    [cdm_languageid]                    NVARCHAR (MAX)   NULL,
    [cdm_languagesother_custom]         NVARCHAR (MAX)   NULL,
    [cdm_lastname]                      NVARCHAR (MAX)   NULL,
    [cdm_linkedinidentity]              NVARCHAR (MAX)   NULL,
    [cdm_managerworkerid]               UNIQUEIDENTIFIER NULL,
    [cdm_managerworkeridname]           NVARCHAR (MAX)   NULL,
    [cdm_medical_custom]                NVARCHAR (MAX)   NULL,
    [cdm_middlename]                    NVARCHAR (MAX)   NULL,
    [cdm_mobilephone]                   NVARCHAR (MAX)   NULL,
    [cdm_namesequencedisplayas]         NVARCHAR (MAX)   NULL,
    [cdm_officegraphidentifier]         NVARCHAR (MAX)   NULL,
    [cdm_originalhiredatetime]          DATETIME2 (7)    NULL,
    [cdm_otherreligion_custom]          NVARCHAR (MAX)   NULL,
    [cdm_primaryemailaddress]           NVARCHAR (MAX)   NULL,
    [cdm_primarytelephone]              NVARCHAR (MAX)   NULL,
    [cdm_profession]                    NVARCHAR (MAX)   NULL,
    [cdm_raceother_custom]              NVARCHAR (MAX)   NULL,
    [cdm_religion_custom]               INT              NULL,
    [cdm_senioritydate]                 DATETIME2 (7)    NULL,
    [cdm_sexualorientationother_custom] NVARCHAR (MAX)   NULL,
    [cdm_sexualorientationv2_custom]    INT              NULL,
    [cdm_socialnetwork01]               INT              NULL,
    [cdm_socialnetwork02]               INT              NULL,
    [cdm_socialnetworkidentity01]       NVARCHAR (MAX)   NULL,
    [cdm_socialnetworkidentity02]       NVARCHAR (MAX)   NULL,
    [cdm_source]                        INT              NULL,
    [cdm_status]                        INT              NULL,
    [cdm_taplacementid_custom]          NVARCHAR (MAX)   NULL,
    [cdm_telephone1]                    NVARCHAR (MAX)   NULL,
    [cdm_telephone2]                    NVARCHAR (MAX)   NULL,
    [cdm_telephone3]                    NVARCHAR (MAX)   NULL,
    [cdm_titleid]                       UNIQUEIDENTIFIER NULL,
    [cdm_titleidname]                   NVARCHAR (MAX)   NULL,
    [cdm_twitteridentity]               NVARCHAR (MAX)   NULL,
    [cdm_type]                          INT              NULL,
    [cdm_websiteurl]                    NVARCHAR (MAX)   NULL,
    [cdm_workerid]                      UNIQUEIDENTIFIER NULL,
    [cdm_workernumber]                  NVARCHAR (MAX)   NULL,
    [cdm_worksfromhome]                 BIT              NULL,
    [cdm_yomifirstname]                 NVARCHAR (MAX)   NULL,
    [cdm_yomifullname]                  NVARCHAR (MAX)   NULL,
    [cdm_yomilastname]                  NVARCHAR (MAX)   NULL,
    [cdm_yomimiddlename]                NVARCHAR (MAX)   NULL,
    [createdby]                         UNIQUEIDENTIFIER NULL,
    [createdbyname]                     NVARCHAR (MAX)   NULL,
    [createdbyyominame]                 NVARCHAR (MAX)   NULL,
    [createdon]                         DATETIME2 (7)    NULL,
    [createdonbehalfby]                 UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]             NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]         NVARCHAR (MAX)   NULL,
    [importsequencenumber]              INT              NULL,
    [modifiedby]                        UNIQUEIDENTIFIER NULL,
    [modifiedbyname]                    NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]                NVARCHAR (MAX)   NULL,
    [modifiedon]                        DATETIME2 (7)    NULL,
    [modifiedonbehalfby]                UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]            NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame]        NVARCHAR (MAX)   NULL,
    [msdyn_linkedinmemberreference]     NVARCHAR (MAX)   NULL,
    [msdyn_userid]                      UNIQUEIDENTIFIER NULL,
    [msdyn_useridname]                  NVARCHAR (MAX)   NULL,
    [msdyn_useridyominame]              NVARCHAR (MAX)   NULL,
    [overriddencreatedon]               DATETIME2 (7)    NULL,
    [ownerid]                           UNIQUEIDENTIFIER NULL,
    [owneridname]                       NVARCHAR (MAX)   NULL,
    [owneridtype]                       NVARCHAR (MAX)   NULL,
    [owneridyominame]                   NVARCHAR (MAX)   NULL,
    [owningbusinessunit]                UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]            NVARCHAR (MAX)   NULL,
    [owningteam]                        UNIQUEIDENTIFIER NULL,
    [owninguser]                        UNIQUEIDENTIFIER NULL,
    [statecode]                         INT              NULL,
    [statuscode]                        INT              NULL,
    [timezoneruleversionnumber]         INT              NULL,
    [utcconversiontimezonecode]         INT              NULL,
    [versionnumber]                     BIGINT           NULL
);

