CREATE TABLE [hr].[stg_tblcdmworkerpersonaldetail] (
    [cdm_birthcity]                       NVARCHAR (MAX)   NULL,
    [cdm_birthcountryregion]              INT              NULL,
    [cdm_birthdate]                       DATETIME2 (7)    NULL,
    [cdm_citizenshipcountryregion]        INT              NULL,
    [cdm_deceaseddate]                    DATETIME2 (7)    NULL,
    [cdm_disabledveteranverificationdate] DATETIME2 (7)    NULL,
    [cdm_education]                       NVARCHAR (MAX)   NULL,
    [cdm_ethnicoriginid]                  UNIQUEIDENTIFIER NULL,
    [cdm_ethnicoriginidname]              NVARCHAR (MAX)   NULL,
    [cdm_expatriateenddate]               DATETIME2 (7)    NULL,
    [cdm_expatriatestartdate]             DATETIME2 (7)    NULL,
    [cdm_fatherbirthcountryregion]        INT              NULL,
    [cdm_gender]                          INT              NULL,
    [cdm_isdisabled]                      BIT              NULL,
    [cdm_isdisabledveteran]               BIT              NULL,
    [cdm_isexpatriaterulingapplicable]    BIT              NULL,
    [cdm_isfulltimestudent]               BIT              NULL,
    [cdm_maritalstatus]                   INT              NULL,
    [cdm_militaryserviceenddate]          DATETIME2 (7)    NULL,
    [cdm_militaryservicestartdate]        DATETIME2 (7)    NULL,
    [cdm_motherbirthcountryregion]        INT              NULL,
    [cdm_nationalitycountryregion]        INT              NULL,
    [cdm_nativelanguageidid]              UNIQUEIDENTIFIER NULL,
    [cdm_nativelanguageididname]          NVARCHAR (MAX)   NULL,
    [cdm_numberofdependents]              INT              NULL,
    [cdm_personalsuffix]                  INT              NULL,
    [cdm_personaltitle]                   INT              NULL,
    [cdm_veteranstatusid]                 UNIQUEIDENTIFIER NULL,
    [cdm_veteranstatusidname]             NVARCHAR (MAX)   NULL,
    [cdm_workerid]                        UNIQUEIDENTIFIER NULL,
    [cdm_workeridname]                    NVARCHAR (MAX)   NULL,
    [cdm_workerpersonaldetailid]          UNIQUEIDENTIFIER NULL,
    [cdm_workerpersonaldetailnumber]      NVARCHAR (MAX)   NULL,
    [createdby]                           UNIQUEIDENTIFIER NULL,
    [createdbyname]                       NVARCHAR (MAX)   NULL,
    [createdbyyominame]                   NVARCHAR (MAX)   NULL,
    [createdon]                           DATETIME2 (7)    NULL,
    [createdonbehalfby]                   UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]               NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]           NVARCHAR (MAX)   NULL,
    [importsequencenumber]                INT              NULL,
    [modifiedby]                          UNIQUEIDENTIFIER NULL,
    [modifiedbyname]                      NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]                  NVARCHAR (MAX)   NULL,
    [modifiedon]                          DATETIME2 (7)    NULL,
    [modifiedonbehalfby]                  UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]              NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame]          NVARCHAR (MAX)   NULL,
    [overriddencreatedon]                 DATETIME2 (7)    NULL,
    [ownerid]                             UNIQUEIDENTIFIER NULL,
    [owneridname]                         NVARCHAR (MAX)   NULL,
    [owneridtype]                         NVARCHAR (MAX)   NULL,
    [owneridyominame]                     NVARCHAR (MAX)   NULL,
    [owningbusinessunit]                  UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]              NVARCHAR (MAX)   NULL,
    [owningteam]                          UNIQUEIDENTIFIER NULL,
    [owninguser]                          UNIQUEIDENTIFIER NULL,
    [statecode]                           INT              NULL,
    [statuscode]                          INT              NULL,
    [timezoneruleversionnumber]           INT              NULL,
    [utcconversiontimezonecode]           INT              NULL,
    [versionnumber]                       BIGINT           NULL
);

