CREATE TABLE [hr].[stg_tblcdmjobposition] (
    [cdm_activation]                   DATETIME2 (7)    NULL,
    [cdm_availableforassignment]       DATETIME2 (7)    NULL,
    [cdm_compensationregionid]         UNIQUEIDENTIFIER NULL,
    [cdm_compensationregionidname]     NVARCHAR (MAX)   NULL,
    [cdm_departmentid]                 UNIQUEIDENTIFIER NULL,
    [cdm_departmentidname]             NVARCHAR (MAX)   NULL,
    [cdm_description]                  NVARCHAR (MAX)   NULL,
    [cdm_eeojobclassification_custom]  INT              NULL,
    [cdm_fulltimeequivalent]           DECIMAL (38, 18) NULL,
    [cdm_function_custom]              INT              NULL,
    [cdm_historicallinemanager_custom] NVARCHAR (MAX)   NULL,
    [cdm_jobid]                        UNIQUEIDENTIFIER NULL,
    [cdm_jobidname]                    NVARCHAR (MAX)   NULL,
    [cdm_jobpositionid]                UNIQUEIDENTIFIER NULL,
    [cdm_jobpositionnumber]            NVARCHAR (MAX)   NULL,
    [cdm_office_custom]                INT              NULL,
    [cdm_opentota_custom]              BIT              NULL,
    [cdm_parentjobpositionid]          UNIQUEIDENTIFIER NULL,
    [cdm_parentjobpositionidname]      NVARCHAR (MAX)   NULL,
    [cdm_positiontypeid]               UNIQUEIDENTIFIER NULL,
    [cdm_positiontypeidname]           NVARCHAR (MAX)   NULL,
    [cdm_retirement]                   DATETIME2 (7)    NULL,
    [cdm_team_custom]                  INT              NULL,
    [cdm_teamv2_custom]                NVARCHAR (MAX)   NULL,
    [cdm_title]                        INT              NULL,
    [cdm_titleid]                      UNIQUEIDENTIFIER NULL,
    [cdm_titleidname]                  NVARCHAR (MAX)   NULL,
    [cdm_vacant_custom]                BIT              NULL,
    [cdm_validfrom]                    DATETIME2 (7)    NULL,
    [cdm_validto]                      DATETIME2 (7)    NULL,
    [createdby]                        UNIQUEIDENTIFIER NULL,
    [createdbyname]                    NVARCHAR (MAX)   NULL,
    [createdbyyominame]                NVARCHAR (MAX)   NULL,
    [createdon]                        DATETIME2 (7)    NULL,
    [createdonbehalfby]                UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]            NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]        NVARCHAR (MAX)   NULL,
    [importsequencenumber]             INT              NULL,
    [modifiedby]                       UNIQUEIDENTIFIER NULL,
    [modifiedbyname]                   NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]               NVARCHAR (MAX)   NULL,
    [modifiedon]                       DATETIME2 (7)    NULL,
    [modifiedonbehalfby]               UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]           NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame]       NVARCHAR (MAX)   NULL,
    [msdyn_additionalmetadata]         NVARCHAR (MAX)   NULL,
    [overriddencreatedon]              DATETIME2 (7)    NULL,
    [ownerid]                          UNIQUEIDENTIFIER NULL,
    [owneridname]                      NVARCHAR (MAX)   NULL,
    [owneridtype]                      NVARCHAR (MAX)   NULL,
    [owneridyominame]                  NVARCHAR (MAX)   NULL,
    [owningbusinessunit]               UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]           NVARCHAR (MAX)   NULL,
    [owningteam]                       UNIQUEIDENTIFIER NULL,
    [owninguser]                       UNIQUEIDENTIFIER NULL,
    [statecode]                        INT              NULL,
    [statuscode]                       INT              NULL,
    [timezoneruleversionnumber]        INT              NULL,
    [utcconversiontimezonecode]        INT              NULL,
    [versionnumber]                    BIGINT           NULL
);

