CREATE TABLE [hr].[stg_tblcdmworkerfixedcompensation] (
    [cdm_companyid]                     UNIQUEIDENTIFIER NULL,
    [cdm_companyidname]                 NVARCHAR (MAX)   NULL,
    [cdm_compensationlevelid]           UNIQUEIDENTIFIER NULL,
    [cdm_compensationlevelidname]       NVARCHAR (MAX)   NULL,
    [cdm_compensationtype]              INT              NULL,
    [cdm_effectivedate]                 DATETIME2 (7)    NULL,
    [cdm_eventid]                       UNIQUEIDENTIFIER NULL,
    [cdm_eventidname]                   NVARCHAR (MAX)   NULL,
    [cdm_expirationdate]                DATETIME2 (7)    NULL,
    [cdm_linenumber]                    DECIMAL (38, 18) NULL,
    [cdm_payfrequencyid]                UNIQUEIDENTIFIER NULL,
    [cdm_payfrequencyidname]            NVARCHAR (MAX)   NULL,
    [cdm_payrate]                       DECIMAL (38, 18) NULL,
    [cdm_payrate_base]                  DECIMAL (38, 18) NULL,
    [cdm_planid]                        UNIQUEIDENTIFIER NULL,
    [cdm_planidname]                    NVARCHAR (MAX)   NULL,
    [cdm_positionid]                    UNIQUEIDENTIFIER NULL,
    [cdm_positionidname]                NVARCHAR (MAX)   NULL,
    [cdm_processtype]                   INT              NULL,
    [cdm_referencepointsetuplineid]     UNIQUEIDENTIFIER NULL,
    [cdm_referencepointsetuplineidname] NVARCHAR (MAX)   NULL,
    [cdm_workerfixedcompensationid]     UNIQUEIDENTIFIER NULL,
    [cdm_workerfixedcompensationnumber] NVARCHAR (MAX)   NULL,
    [cdm_workerid]                      UNIQUEIDENTIFIER NULL,
    [cdm_workeridname]                  NVARCHAR (MAX)   NULL,
    [createdby]                         UNIQUEIDENTIFIER NULL,
    [createdbyname]                     NVARCHAR (MAX)   NULL,
    [createdbyyominame]                 NVARCHAR (MAX)   NULL,
    [createdon]                         DATETIME2 (7)    NULL,
    [createdonbehalfby]                 UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]             NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]         NVARCHAR (MAX)   NULL,
    [exchangerate]                      DECIMAL (38, 18) NULL,
    [importsequencenumber]              INT              NULL,
    [modifiedby]                        UNIQUEIDENTIFIER NULL,
    [modifiedbyname]                    NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]                NVARCHAR (MAX)   NULL,
    [modifiedon]                        DATETIME2 (7)    NULL,
    [modifiedonbehalfby]                UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]            NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame]        NVARCHAR (MAX)   NULL,
    [overriddencreatedon]               DATETIME2 (7)    NULL,
    [ownerid]                           UNIQUEIDENTIFIER NULL,
    [owneridname]                       NVARCHAR (MAX)   NULL,
    [owneridtype]                       NVARCHAR (MAX)   NULL,
    [owneridyominame]                   NVARCHAR (MAX)   NULL,
    [owningbusinessunit]                UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]            NVARCHAR (MAX)   NULL,
    [owningteam]                        UNIQUEIDENTIFIER NULL,
    [owninguser]                        UNIQUEIDENTIFIER NULL,
    [statecode]                         INT              NULL,
    [statuscode]                        INT              NULL,
    [timezoneruleversionnumber]         INT              NULL,
    [transactioncurrencyid]             UNIQUEIDENTIFIER NULL,
    [transactioncurrencyidname]         NVARCHAR (MAX)   NULL,
    [utcconversiontimezonecode]         INT              NULL,
    [versionnumber]                     BIGINT           NULL
);

