CREATE TABLE [hr].[stg_tblcdmjob] (
    [cdm_allowunlimitedpositions]   BIT              NULL,
    [cdm_defaultfulltimeequivalent] DECIMAL (38, 18) NULL,
    [cdm_description]               NVARCHAR (MAX)   NULL,
    [cdm_jobdescription]            NVARCHAR (MAX)   NULL,
    [cdm_jobfunctionid]             UNIQUEIDENTIFIER NULL,
    [cdm_jobfunctionidname]         NVARCHAR (MAX)   NULL,
    [cdm_jobid]                     UNIQUEIDENTIFIER NULL,
    [cdm_jobtypeid]                 UNIQUEIDENTIFIER NULL,
    [cdm_jobtypeidname]             NVARCHAR (MAX)   NULL,
    [cdm_maximumnumberofpositions]  INT              NULL,
    [cdm_name]                      NVARCHAR (MAX)   NULL,
    [cdm_title]                     INT              NULL,
    [cdm_titleid]                   UNIQUEIDENTIFIER NULL,
    [cdm_titleidname]               NVARCHAR (MAX)   NULL,
    [cdm_validfrom]                 DATETIME2 (7)    NULL,
    [cdm_validto]                   DATETIME2 (7)    NULL,
    [createdby]                     UNIQUEIDENTIFIER NULL,
    [createdbyname]                 NVARCHAR (MAX)   NULL,
    [createdbyyominame]             NVARCHAR (MAX)   NULL,
    [createdon]                     DATETIME2 (7)    NULL,
    [createdonbehalfby]             UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]         NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]     NVARCHAR (MAX)   NULL,
    [importsequencenumber]          INT              NULL,
    [modifiedby]                    UNIQUEIDENTIFIER NULL,
    [modifiedbyname]                NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]            NVARCHAR (MAX)   NULL,
    [modifiedon]                    DATETIME2 (7)    NULL,
    [modifiedonbehalfby]            UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]        NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame]    NVARCHAR (MAX)   NULL,
    [overriddencreatedon]           DATETIME2 (7)    NULL,
    [ownerid]                       UNIQUEIDENTIFIER NULL,
    [owneridname]                   NVARCHAR (MAX)   NULL,
    [owneridtype]                   NVARCHAR (MAX)   NULL,
    [owneridyominame]               NVARCHAR (MAX)   NULL,
    [owningbusinessunit]            UNIQUEIDENTIFIER NULL,
    [owningbusinessunitname]        NVARCHAR (MAX)   NULL,
    [owningteam]                    UNIQUEIDENTIFIER NULL,
    [owninguser]                    UNIQUEIDENTIFIER NULL,
    [statecode]                     INT              NULL,
    [statuscode]                    INT              NULL,
    [timezoneruleversionnumber]     INT              NULL,
    [utcconversiontimezonecode]     INT              NULL,
    [versionnumber]                 BIGINT           NULL
);

