CREATE TABLE [hr].[stg_systemuser] (
    [accessmode]                        INT              NULL,
    [activedirectoryguid]               UNIQUEIDENTIFIER NULL,
    [address1_addressid]                UNIQUEIDENTIFIER NULL,
    [address1_addresstypecode]          INT              NULL,
    [address1_city]                     NVARCHAR (MAX)   NULL,
    [address1_composite]                NVARCHAR (MAX)   NULL,
    [address1_country]                  NVARCHAR (MAX)   NULL,
    [address1_county]                   NVARCHAR (MAX)   NULL,
    [address1_fax]                      NVARCHAR (MAX)   NULL,
    [address1_latitude]                 FLOAT (53)       NULL,
    [address1_line1]                    NVARCHAR (MAX)   NULL,
    [address1_line2]                    NVARCHAR (MAX)   NULL,
    [address1_line3]                    NVARCHAR (MAX)   NULL,
    [address1_longitude]                FLOAT (53)       NULL,
    [address1_name]                     NVARCHAR (MAX)   NULL,
    [address1_postalcode]               NVARCHAR (MAX)   NULL,
    [address1_postofficebox]            NVARCHAR (MAX)   NULL,
    [address1_shippingmethodcode]       INT              NULL,
    [address1_stateorprovince]          NVARCHAR (MAX)   NULL,
    [address1_telephone1]               NVARCHAR (MAX)   NULL,
    [address1_telephone2]               NVARCHAR (MAX)   NULL,
    [address1_telephone3]               NVARCHAR (MAX)   NULL,
    [address1_upszone]                  NVARCHAR (MAX)   NULL,
    [address1_utcoffset]                INT              NULL,
    [address2_addressid]                UNIQUEIDENTIFIER NULL,
    [address2_addresstypecode]          INT              NULL,
    [address2_city]                     NVARCHAR (MAX)   NULL,
    [address2_composite]                NVARCHAR (MAX)   NULL,
    [address2_country]                  NVARCHAR (MAX)   NULL,
    [address2_county]                   NVARCHAR (MAX)   NULL,
    [address2_fax]                      NVARCHAR (MAX)   NULL,
    [address2_latitude]                 FLOAT (53)       NULL,
    [address2_line1]                    NVARCHAR (MAX)   NULL,
    [address2_line2]                    NVARCHAR (MAX)   NULL,
    [address2_line3]                    NVARCHAR (MAX)   NULL,
    [address2_longitude]                FLOAT (53)       NULL,
    [address2_name]                     NVARCHAR (MAX)   NULL,
    [address2_postalcode]               NVARCHAR (MAX)   NULL,
    [address2_postofficebox]            NVARCHAR (MAX)   NULL,
    [address2_shippingmethodcode]       INT              NULL,
    [address2_stateorprovince]          NVARCHAR (MAX)   NULL,
    [address2_telephone1]               NVARCHAR (MAX)   NULL,
    [address2_telephone2]               NVARCHAR (MAX)   NULL,
    [address2_telephone3]               NVARCHAR (MAX)   NULL,
    [address2_upszone]                  NVARCHAR (MAX)   NULL,
    [address2_utcoffset]                INT              NULL,
    [applicationid]                     UNIQUEIDENTIFIER NULL,
    [applicationiduri]                  NVARCHAR (MAX)   NULL,
    [azureactivedirectoryobjectid]      UNIQUEIDENTIFIER NULL,
    [azuredeletedon]                    DATETIME2 (7)    NULL,
    [azurestate]                        INT              NULL,
    [businessunitid]                    UNIQUEIDENTIFIER NULL,
    [businessunitidname]                NVARCHAR (MAX)   NULL,
    [calendarid]                        UNIQUEIDENTIFIER NULL,
    [caltype]                           INT              NULL,
    [cdm_company]                       UNIQUEIDENTIFIER NULL,
    [cdm_companyname]                   NVARCHAR (MAX)   NULL,
    [createdby]                         UNIQUEIDENTIFIER NULL,
    [createdbyname]                     NVARCHAR (MAX)   NULL,
    [createdbyyominame]                 NVARCHAR (MAX)   NULL,
    [createdon]                         DATETIME2 (7)    NULL,
    [createdonbehalfby]                 UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]             NVARCHAR (MAX)   NULL,
    [createdonbehalfbyyominame]         NVARCHAR (MAX)   NULL,
    [defaultfilterspopulated]           BIT              NULL,
    [defaultmailbox]                    UNIQUEIDENTIFIER NULL,
    [defaultmailboxname]                NVARCHAR (MAX)   NULL,
    [defaultodbfoldername]              NVARCHAR (MAX)   NULL,
    [deletedstate]                      INT              NULL,
    [disabledreason]                    NVARCHAR (MAX)   NULL,
    [displayinserviceviews]             BIT              NULL,
    [domainname]                        NVARCHAR (MAX)   NULL,
    [emailrouteraccessapproval]         INT              NULL,
    [employeeid]                        NVARCHAR (MAX)   NULL,
    [entityimage_timestamp]             BIGINT           NULL,
    [entityimage_url]                   NVARCHAR (MAX)   NULL,
    [entityimageid]                     UNIQUEIDENTIFIER NULL,
    [exchangerate]                      DECIMAL (38, 18) NULL,
    [firstname]                         NVARCHAR (MAX)   NULL,
    [fullname]                          NVARCHAR (MAX)   NULL,
    [governmentid]                      NVARCHAR (MAX)   NULL,
    [homephone]                         NVARCHAR (MAX)   NULL,
    [identityid]                        INT              NULL,
    [importsequencenumber]              INT              NULL,
    [incomingemaildeliverymethod]       INT              NULL,
    [internalemailaddress]              NVARCHAR (MAX)   NULL,
    [invitestatuscode]                  INT              NULL,
    [isactivedirectoryuser]             BIT              NULL,
    [isdisabled]                        BIT              NULL,
    [isemailaddressapprovedbyo365admin] BIT              NULL,
    [isintegrationuser]                 BIT              NULL,
    [islicensed]                        BIT              NULL,
    [issyncwithdirectory]               BIT              NULL,
    [jobtitle]                          NVARCHAR (MAX)   NULL,
    [lastname]                          NVARCHAR (MAX)   NULL,
    [latestupdatetime]                  DATETIME2 (7)    NULL,
    [middlename]                        NVARCHAR (MAX)   NULL,
    [mobilealertemail]                  NVARCHAR (MAX)   NULL,
    [mobileofflineprofileid]            UNIQUEIDENTIFIER NULL,
    [mobileofflineprofileidname]        NVARCHAR (MAX)   NULL,
    [mobilephone]                       NVARCHAR (MAX)   NULL,
    [modifiedby]                        UNIQUEIDENTIFIER NULL,
    [modifiedbyname]                    NVARCHAR (MAX)   NULL,
    [modifiedbyyominame]                NVARCHAR (MAX)   NULL,
    [modifiedon]                        DATETIME2 (7)    NULL,
    [modifiedonbehalfby]                UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]            NVARCHAR (MAX)   NULL,
    [modifiedonbehalfbyyominame]        NVARCHAR (MAX)   NULL,
    [nickname]                          NVARCHAR (MAX)   NULL,
    [organizationid]                    UNIQUEIDENTIFIER NULL,
    [organizationidname]                NVARCHAR (MAX)   NULL,
    [outgoingemaildeliverymethod]       INT              NULL,
    [overriddencreatedon]               DATETIME2 (7)    NULL,
    [parentsystemuserid]                UNIQUEIDENTIFIER NULL,
    [parentsystemuseridname]            NVARCHAR (MAX)   NULL,
    [parentsystemuseridyominame]        NVARCHAR (MAX)   NULL,
    [passporthi]                        INT              NULL,
    [passportlo]                        INT              NULL,
    [personalemailaddress]              NVARCHAR (MAX)   NULL,
    [photourl]                          NVARCHAR (MAX)   NULL,
    [positionid]                        UNIQUEIDENTIFIER NULL,
    [positionidname]                    NVARCHAR (MAX)   NULL,
    [preferredaddresscode]              INT              NULL,
    [preferredemailcode]                INT              NULL,
    [preferredphonecode]                INT              NULL,
    [processid]                         UNIQUEIDENTIFIER NULL,
    [queueid]                           UNIQUEIDENTIFIER NULL,
    [queueidname]                       NVARCHAR (MAX)   NULL,
    [salutation]                        NVARCHAR (MAX)   NULL,
    [setupuser]                         BIT              NULL,
    [sharepointemailaddress]            NVARCHAR (MAX)   NULL,
    [skills]                            NVARCHAR (MAX)   NULL,
    [stageid]                           UNIQUEIDENTIFIER NULL,
    [systemuserid]                      UNIQUEIDENTIFIER NULL,
    [territoryid]                       UNIQUEIDENTIFIER NULL,
    [territoryidname]                   NVARCHAR (MAX)   NULL,
    [timezoneruleversionnumber]         INT              NULL,
    [title]                             NVARCHAR (MAX)   NULL,
    [transactioncurrencyid]             UNIQUEIDENTIFIER NULL,
    [transactioncurrencyidname]         NVARCHAR (MAX)   NULL,
    [traversedpath]                     NVARCHAR (MAX)   NULL,
    [userlicensetype]                   INT              NULL,
    [userpuid]                          NVARCHAR (MAX)   NULL,
    [utcconversiontimezonecode]         INT              NULL,
    [versionnumber]                     BIGINT           NULL,
    [windowsliveid]                     NVARCHAR (MAX)   NULL,
    [yammeremailaddress]                NVARCHAR (MAX)   NULL,
    [yammeruserid]                      NVARCHAR (MAX)   NULL,
    [yomifirstname]                     NVARCHAR (MAX)   NULL,
    [yomifullname]                      NVARCHAR (MAX)   NULL,
    [yomilastname]                      NVARCHAR (MAX)   NULL,
    [yomimiddlename]                    NVARCHAR (MAX)   NULL
);

