

CREATE VIEW [dbo].[Worker]
AS

	WITH Worker
		AS
		(
		SELECT 
			  w.PERSONNELNUMBER
			, w.PARTYNUMBER
			, CASE WHEN u.USEREMAIL IS NULL THEN 'nomercuryid@phaidoninternational.com' ELSE u.USEREMAIL END AS USEREMAIL
			, w.NAME
			, CASE WHEN w.KNOWNAS='' THEN w.NAME ELSE w.KNOWNAS END as KNOWNAS
			, w.SEXUALORIENTATIONV2_CUSTOM
			, w.SEXUALORIENTATIONOTHER_CUSTOM
			, w.GENDEROTHER_CUSTOM
			, w.MEDICAL_CUSTOM
			, w.ASSIGNMENTS_CUSTOM
			, w.CAREERTRACK_CUSTOM
			, w.ISDISABLED
			, w.MARITALSTATUS
			, w.NATIONALITYCOUNTRYREGION
			, w.NUMBEROFDEPENDENTS
			, w.PERSONALTITLE
			, eo.DESCRIPTION AS ETHINCITY
			, w.NATIVELANGUAGEID AS LANGUAGE_NAME
			, w.PRIMARYCONTACTEMAIL
			, w.PRIMARYCONTACTPHONE
			, w.ADDRESSSTREET
			, w.ADDRESSCITY
			, w.ADDRESSCOUNTY
			, w.ADDRESSSTATE
			, w.ADDRESSZIPCODE
			, w.ADDRESSCOUNTRYREGIONID
			, w.BIRTHDATE
			, w.OFFICELOCATION as W_Office
			, w.EEOARMY_CUSTOM
			, w.EEOCOLLEGE_CUSTOM
			, w.EEOGENDER_CUSTOM
			, w.EEORACE_CUSTOM
			, w.EEORELIGION_CUSTOM
			, w.EEOSEXUALORIENTATION_CUSTOM
			, w.EEOTRANS_CUSTOM
			, w.EEOCAREADULT_CUSTOM
			, w.EEOCAREPOC_CUSTOM
			, w.LANGUAGESOTHER_CUSTOM
			, w.RACEOTHER_CUSTOM
			, w.OTHERRELIGION_CUSTOM
			, CASE 
				WHEN w.GENDER = 1 THEN 'Male' 
				WHEN w.GENDER = 2 THEN 'Female' 
				WHEN w.GENDER = 3 THEN 'Not-Specified' 
			  ELSE 'Other' END AS Gender
			, fe.SD
			, fe.ED
			, cp.POSITIONID
			, cp.OFFICE_CUSTOM
			, cp.TEAM_CUSTOM
			, cp.TEAMV2_CUSTOM
			, b.NAME AS Brand
			, cp.Corporate_Title
			, cp.Functional_Title
			, cpm.Manager_ID
			, cpm.NAME AS Manager_Name
			, cpm.KNOWNAS AS Manager_KnownAs
			, cpm.Manager_Email
			, cs.PAYRATE
			, pp.PROBATIONPERIOD
			, le.EXTENDEDPROBATIONEND_CUSTOM
			, le.ORIGPROBATIONENDDATE_CUSTOM
			, le.PROBATIONCOMPLETE_CUSTOM
			, le.PROBATIONPASSEDDATE_CUSTOM
			, le.EXITTYPE_CUSTOM
			, le.LEAVINGREASON_CUSTOM
			, le.LEAVINGREASONOTHER_CUSTOM
			, le.EMPLOYERUNITOFNOTICE
			, le.WORKERUNITOFNOTICE
			, le.EMPLOYERNOTICEAMOUNT
			, le.WORKERNOTICEAMOUNT
			, le.PAYROLLID_CUSTOM
			, le.TRANSITIONDATE
			, le.LASTDATEWORKED
			, c.STARTDATE AS MDBC
			, CASE WHEN fe.REHIRE_CUSTOM = 1 THEN 'Rehire' else Null END AS REHIRE_CUSTOM
			 --NEW COLUMNS
			,CASE 
				 WHEN TEAMV2_CUSTOM='' THEN NULL 
				 WHEN SUBSTRING(TEAMV2_CUSTOM,7,1)= '' THEN NULL
			  ELSE CONCAT('Sub-Team ',SUBSTRING(TEAMV2_CUSTOM,7,1)) END as Sub_Team_Sql
			,CASE 
				WHEN LTRIM(RTRIM(SUBSTRING(TEAMV2_CUSTOM,0,CHARINDEX('-',TEAMV2_CUSTOM,0)))) is NULL THEN 'Z00000'
				WHEN LTRIM(RTRIM(SUBSTRING(TEAMV2_CUSTOM,0,CHARINDEX('-',TEAMV2_CUSTOM,0)))) ='' THEN 'Z00000'
			 ELSE LTRIM(RTRIM(SUBSTRING(TEAMV2_CUSTOM,0,CHARINDEX('-',TEAMV2_CUSTOM,0)))) END as Team_Join_Sql 
	--select  *
	FROM [dbo].[HcmWorkerStaging] w 
	LEFT JOIN dbo.[DirPersonUserStaging] u 
				ON u.PERSONNELNUMBER COLLATE DATABASE_DEFAULT = w.PERSONNELNUMBER COLLATE DATABASE_DEFAULT
	LEFT JOIN [dbo].[HcmEthnicOriginStaging] eo 
				ON eo.ETHNICORIGINID = w.ETHNICORIGINID
	LEFT JOIN (
			SELECT 
					  nw.PERSONNELNUMBER
					, CASE WHEN re.PERSONNELNUMBER IS NULL THEN nw.SD ELSE re.RE_SD END AS SD
					, nw.ED
					, re.REHIRE_CUSTOM
			FROM (
				SELECT w.PERSONNELNUMBER
					, MIN(e.EMPLOYMENTSTARTDATE) AS SD
					, MAX(e.EMPLOYMENTENDDATE) AS ED
				FROM [dbo].[HcmWorkerStaging] w 
				LEFT JOIN dbo.HcmEmploymentStaging e 
						ON w.PERSONNELNUMBER = e.PERSONNELNUMBER 
				LEFT JOIN dbo.HcmEmploymentStaging re 
						ON w.PERSONNELNUMBER = re.PERSONNELNUMBER 
							AND re.REHIRE_CUSTOM  = 1
				GROUP BY w.PERSONNELNUMBER
				) nw 
			LEFT JOIN ( 
						SELECT PERSONNELNUMBER
							, MAX(EMPLOYMENTSTARTDATE) AS RE_SD 
							, REHIRE_CUSTOM
						FROM dbo.HcmEmploymentStaging 
							WHERE REHIRE_CUSTOM = 1
						GROUP BY PERSONNELNUMBER, REHIRE_CUSTOM
					  ) re ON nw.PERSONNELNUMBER = re.PERSONNELNUMBER 
				) fe ON fe.PERSONNELNUMBER = w.PERSONNELNUMBER
	LEFT JOIN (
					SELECT 
						 w.PERSONNELNUMBER
						,CASE WHEN ns.POSITIONID IS NULL THEN CASE WHEN wp.POSITIONID IS NULL THEN nop.POSITIONID 
																ELSE wp.POSITIONID END 
							ELSE ns.POSITIONID END AS POSITIONID
						,CASE WHEN nsp.OFFICE_CUSTOM IS NULL THEN p.OFFICE_CUSTOM 
							ELSE nsp.OFFICE_CUSTOM END AS OFFICE_CUSTOM
						,CASE WHEN nsp.TEAM_CUSTOM IS NULL THEN p.TEAM_CUSTOM ELSE nsp.TEAM_CUSTOM END AS TEAM_CUSTOM
						,CASE WHEN nsp.TEAMV2_CUSTOM IS NULL THEN CASE WHEN p.POSITIONID IS NULL THEN mdp.TEAMV2_CUSTOM 
																	ELSE p.TEAMV2_CUSTOM END 
							ELSE nsp.TEAMV2_CUSTOM END AS TEAMV2_CUSTOM
						,CASE WHEN nsp.DEPARTMENTNUMBER IS NULL THEN p.DEPARTMENTNUMBER 
							ELSE nsp.DEPARTMENTNUMBER END AS BRANDID
						,CASE WHEN CASE WHEN nsp.JOBID IS NULL THEN pj.DESCRIPTION 
									ELSE nspj.DESCRIPTION END IS NULL THEN CASE WHEN nsp.JOBID IS NULL THEN p.JOBID 
																			ELSE nsp.JOBID END 
							ELSE CASE WHEN nsp.JOBID IS NULL THEN pj.DESCRIPTION 
								ELSE nspj.DESCRIPTION END 
						 END AS Functional_Title
						,CASE WHEN nsp.TITLEID IS NULL THEN p.TITLEID 
							ELSE nsp.TITLEID END AS Corporate_Title
					FROM [dbo].[HcmWorkerStaging] w 
					LEFT JOIN HcmEmploymentStaging nse 
							ON w.PERSONNELNUMBER = nse.PERSONNELNUMBER 
								AND nse.EMPLOYMENTSTARTDATE>CURRENT_TIMESTAMP
					LEFT JOIN dbo.HcmPositionWorkerAssignmentV2Staging wp 
							ON w.PERSONNELNUMBER = wp.PERSONNELNUMBER 
								AND wp.ISPRIMARYPOSITION = 1
					LEFT JOIN dbo.HcmPositionWorkerAssignmentV2Staging ns 
							ON nse.PERSONNELNUMBER = ns.PERSONNELNUMBER 
								AND ns.VALIDFROM > CURRENT_TIMESTAMP
					LEFT JOIN dbo.HcmPositionV2Staging p 
							ON p.POSITIONID = wp.POSITIONID
					LEFT JOIN dbo.HcmJobStaging pj 
							ON p.JOBID = pj.JOBID
					LEFT JOIN dbo.HcmPositionV2Staging nsp 
							ON nsp.POSITIONID = ns.POSITIONID
					LEFT JOIN dbo.HcmJobStaging nspj 
							ON p.JOBID = nspj.JOBID
					LEFT JOIN (
								SELECT lp.POSITIONID
									, lp.PERSONNELNUMBER 
								FROM dbo.HcmPositionWorkerAssignmentV2Staging lp 
								INNER JOIN (
											SELECT PERSONNELNUMBER
												, MAX(VALIDTO) AS MD 
											FROM dbo.HcmPositionWorkerAssignmentV2Staging
											GROUP BY PERSONNELNUMBER
							  ) md ON md.PERSONNELNUMBER = lp.PERSONNELNUMBER 
									AND lp.VALIDTO = md.MD
				) nop ON nop.PERSONNELNUMBER = w.PERSONNELNUMBER
		LEFT JOIN dbo.HcmPositionV2Staging mdp 
				ON mdp.POSITIONID = nop.POSITIONID
		) cp ON cp.PERSONNELNUMBER = w.PERSONNELNUMBER 
	LEFT JOIN OMDepartmentStaging b ON b.OPERATINGUNITNUMBER = cp.BRANDID
	LEFT JOIN (
				SELECT ph.POSITIONID
					, w.NAME
					, w.KNOWNAS
					, p.PERSONNELNUMBER AS Manager_ID
					, u.USEREMAIL AS Manager_Email
				FROM [dbo].[HcmPositionHierarchyStaging] ph 
				INNER JOIN ( 
							SELECT POSITIONID
								, MAX(VALIDTO) AS LR 
							FROM [dbo].[HcmPositionHierarchyStaging]
							GROUP BY POSITIONID
						   ) lr ON lr.POSITIONID = ph.POSITIONID 
								AND lr.LR = ph.VALIDTO
	LEFT JOIN dbo.HcmPositionWorkerAssignmentV2Staging p 
			ON p.POSITIONID = ph.PARENTPOSITIONID 
					AND ISPRIMARYPOSITION = 1
	LEFT JOIN [dbo].[HcmWorkerStaging] w 
			ON w.PERSONNELNUMBER = p.PERSONNELNUMBER	
	LEFT JOIN dbo.DirPersonUserStaging u 
			ON u.PERSONNELNUMBER COLLATE DATABASE_DEFAULT= w.PERSONNELNUMBER COLLATE DATABASE_DEFAULT
	) cpm ON cpm.POSITIONID = cp.POSITIONID
	LEFT JOIN (
				SELECT    CONVERT(decimal,e.PAYRATE) AS PAYRATE
						, e.POSITIONID
				FROM [dbo].[HcmCompFixedEmplStaging] e
				INNER JOIN (
							SELECT POSITIONID
								 , MAX(EXPIRATIONDATE) AS LR
							FROM [dbo].[HcmCompFixedEmplStaging] 
							GROUP BY POSITIONID
							) lr ON lr.POSITIONID = e.POSITIONID 
									AND e.EXPIRATIONDATE = lr.LR
			 ) cs ON cs.POSITIONID = cp.POSITIONID 
	LEFT JOIN (
			SELECT e.PERSONNELNUMBER, e.PROBATIONPERIOD 
			FROM [dbo].[HcmEmployeeStaging] e
			INNER JOIN (
						SELECT PERSONNELNUMBER, MAX(EMPLOYMENTENDDATE) AS LR
						FROM [dbo].[HcmEmployeeStaging] 
						GROUP BY PERSONNELNUMBER 
						) lr ON e.PERSONNELNUMBER = lr.PERSONNELNUMBER AND e.EMPLOYMENTENDDATE = lr.LR
				) pp ON pp.PERSONNELNUMBER = w.PERSONNELNUMBER 
	LEFT JOIN (
			SELECT   e.PERSONNELNUMBER
					,e.EXTENDEDPROBATIONEND_CUSTOM
					,e.ORIGPROBATIONENDDATE_CUSTOM
					,e.PROBATIONCOMPLETE_CUSTOM
					,e.PROBATIONPASSEDDATE_CUSTOM
					,e.EXITTYPE_CUSTOM
					,e.LEAVINGREASON_CUSTOM
					,e.LEAVINGREASONOTHER_CUSTOM
					,ed.WORKERNOTICEAMOUNT
					,CASE WHEN ed.WORKERUNITOFNOTICE = 1 THEN 'Months' ELSE 'Weeks' END AS WORKERUNITOFNOTICE
					,ed.EMPLOYERNOTICEAMOUNT
					,CASE WHEN ed.EMPLOYERUNITOFNOTICE = 1 THEN 'Months' ELSE 'Weeks' END AS EMPLOYERUNITOFNOTICE
					,e.PAYROLLID_CUSTOM
					,ed.LASTDATEWORKED
					,ed.TRANSITIONDATE
			FROM [dbo].[HcmEmploymentStaging] e
			INNER JOIN (
						SELECT PERSONNELNUMBER
							, MAX(EMPLOYMENTENDDATE) AS LR
						FROM [dbo].[HcmEmploymentStaging] 
						GROUP BY PERSONNELNUMBER 
					   ) lr ON e.PERSONNELNUMBER = lr.PERSONNELNUMBER 
					AND e.EMPLOYMENTENDDATE = lr.LR
			INNER JOIN ( 
						SELECT PERSONNELNUMBER
							 , EMPLOYMENTENDDATE
							 , WORKERNOTICEAMOUNT
							 , WORKERUNITOFNOTICE
							 , EMPLOYERNOTICEAMOUNT
							 , EMPLOYERUNITOFNOTICE
							 , LASTDATEWORKED
							 , TRANSITIONDATE
						FROM HcmEmploymentDetailStaging ed
						WHERE VALIDTO = '2154-12-31 23:59:59.000'
					  ) ed ON ed.PERSONNELNUMBER = lr.PERSONNELNUMBER AND ed.EMPLOYMENTENDDATE = lr.LR
) le ON le.PERSONNELNUMBER = w.PERSONNELNUMBER 
LEFT JOIN HcmPersonCertificateStaging c 
		ON c.certificatetypeid = 'MDBC' AND c.PARTYNUMBER = w.PARTYNUMBER
WHERE w.PERSONNELNUMBER <> 'E-002279'
),NONDUPES AS
			(
			Select PERSONNELNUMBER
				, COUNT(PERSONNELNUMBER) PN
			FROM Worker
			GROUP BY  PERSONNELNUMBER
			HAVING COUNT(PERSONNELNUMBER) = 1
			)
SELECT W.* 
FROM Worker W
INNER JOIN NONDUPES ND
		ON ND.PERSONNELNUMBER = W.PERSONNELNUMBER
--WHERE W.PARTYNUMBER<>0


